version: "3.8"

services:
    gmao-app:
        build: .
        ports:
            - "8501:8501"
        volumes:
            - ./data:/app/data
        environment:
            - PYTHONUNBUFFERED=1
        restart: unless-stopped
